### ISSUE TITLE
launch.py没有--controlnet-dir这个参数

### ISSUE THREAD

**Issue by husonchen** [tzwm/sd-scripts#6]
执行到bash /root/tzwm-autodl-sd-webui/a1111-pack/scripts/restart-webui.sh的时候报错
launch.py: error: unrecognized arguments: --controlnet-dir /root/autodl-tmp/models/controlnet --controlnet-annotator-models-path /root/autodl-tmp/models/controlnet_annotator
我检测了stable-diffusion 1.6.0和其他各个版本的代码，cmd_args.py里都是没有声明--controlnet-dir参数的，请问这里是如何启动的

**Comment by tzwm** [comment]
[controlnet](https://github.com/Mikubill/sd-webui-controlnet)  这个插件带的吧。
