### ISSUE TITLE
manager中无法更新comfyui

### ISSUE THREAD

**Issue by xianienie** [tzwm/sd-scripts#7]
![image](https://github.com/tzwm/sd-scripts/assets/113016462/285588c7-94ee-4c91-bc77-9ef98360e0f2)
![image](https://github.com/tzwm/sd-scripts/assets/113016462/e4cffab8-f520-4f40-8ba6-54645f3f8098)

**Comment by tzwm** [comment]
v9 版本更新后就好了，镜像提交审核中了。
